name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - TAG: $(date +%s)
      run: docker build . --file Dockerfile --tag test-docker:$TAG && docker tag test-docker:$TAG test-docker:$TAG && docker push paulotolentino/test-docker:$TAG
