name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag paulotolentino/test-docker
        && docker login -u paulotolentino -p 3832578592068575
        && docker push paulotolentino/test-docker
